- name: "Sending an e-mail using Gmail SMTP servers"
  community.general.mail:
    host: "{{ smtp_server }}"
    port: "{{ smtp_port }}"
    username: "{{ smtp_username }}"
    password: "{{ smtp_password }}"
    to: "{{ mail_to }}"
    subject: "{{ mail_subject }}"
    body: "{{ mail_body }}"
